--- 
- hosts: all
  gather_facts: no
  become: yes
  become_user: isucon
  tags:
    - dev
  tasks:
    - synchronize: src=../../../webapp/ dest=/home/isucon/webapp owner=no group=no links=yes
    - synchronize: src=../../../bin/ dest=/home/isucon/bin owner=no group=no
    - synchronize: src=../files/env.sh dest=/home/isucon/env.sh owner=no group=no
    - file: path=/home/isucon owner=isucon group=isucon state=directory recurse=yes
      become_user: root
    - name: go
      shell: PATH=/home/isucon/.local/go/bin:$PATH GOROOT=/home/isucon/.local/go GOPATH=/home/isucon/webapp/go make all
      args:
        chdir: /home/isucon/webapp/go
- hosts: all
  gather_facts: no
  become: yes
  tags:
    - prod
  tasks:
    - copy: src=../../../bin/ dest=/home/isucon/bin owner=isucon group=isucon mode=755
    - copy: src=../files/env.sh dest=/home/isucon/env.sh owner=isucon group=isucon mode=755
    - unarchive:
        copy=no
        src=https://isucon6qimage.example.com/isucon6q/webapp.tar.gz
        dest=/home/isucon/
        creates=/home/isucon/webapp
        owner=isucon
        group=isucon

- hosts: all
  gather_facts: no
  become: yes
  tags:
    - always
  tasks:
    - name: isupam (systemd)
      copy: src=../files/isupam.service dest=/etc/systemd/system/isupam.service owner=root mode=644
    - name: go isuda (systemd)
      copy: src=../files/isuda.go.service dest=/etc/systemd/system/isuda.go.service owner=root mode=644
    - name: go isutar (systemd)
      copy: src=../files/isutar.go.service dest=/etc/systemd/system/isutar.go.service owner=root mode=644
    - name: default application selection (isupam)
      service: name=isupam state=running enabled=true
    - name: default application selection (isuda)
      service: name=isuda.go state=running enabled=true
    - name: default application selection (isutar)
      service: name=isutar.go state=running enabled=true
